### ISSUE TITLE
Some hardcoded channels in test_models.py

### ISSUE THREAD

**Issue by robmarkcole** [IsaacCorley/pytorch-enhance#9]
If a user runes the tests with `CHANNELS != 3` they will fail as there are some hardcoded channels, e.g. `assert sr.shape == (1, 3, 64, 64)`. These could be updated to `assert sr.shape == (1, CHANNELS, 64, 64)`

**Comment by isaaccorley** [comment]
Revamped the model tests so it runs each model with different scale factor, number of channels, and batch size. Appears to pass now including all tests with 1 channel input. Let me know if you run into any other problems but should be good to go now. Note that SRResNet and EDSR don't support scale factor of 3 at the moment due to pixel shuffle op.
